### ISSUE TITLE
chromium-x11 receipe is broken duo to missing file

### ISSUE THREAD

**Issue by mellowcandle** [96boards/meta-rpb#157]
The commit:  recipes-overlayed: add chromium-X11 v.64 and chromium-ozone-wayland v.65 
is missing the file: 0001-memcpy-used-without-including-string.h.patch

Causes:
chromium-x11-64.0.3282.167-r0 do_fetch: Failed to fetch URL file://0001-memcpy-used-without-including-string.h.patch

**Comment by andrey-konovalov** [comment]
Yes, you are right. But this have been fixed recently:
https://github.com/96boards/meta-rpb/pull/155
https://github.com/96boards/meta-rpb/commit/5cc4cfe90603c343d098ada9bad6aa76acf12ae4
