### ISSUE TITLE
nodejs compilation failure

### ISSUE THREAD

**Issue by mellowcandle** [96boards/meta-rpb#158]
This occurs only when path is long (on CI machine)
I think it's because of chromium dependency in nodejs.
looks like: https://github.com/imyller/meta-nodejs/issues/9

```
| make[1]: execvp: printf: Argument list too long
| make[1]: *** [/local/mnt/workspace/lnxbuild/project/trees_in_use/free_tree_le_manifest_IMM.LE.1.0_dragonboard-410c_commander_31004980/checkout/build/tmp-glibc/work/x86_64-linux/nodejs-native/8.4.0-r0/node-v8.4.0/out/Release/obj.target/deps/v8/src/libv8_base.a] Error 127
| rm e24ac04e0e64fe0c1664f23f62b67182f58e38ed.intermediate
| make[1]: Leaving directory `/local/mnt/workspace/lnxbuild/project/trees_in_use/free_tree_le_manifest_IMM.LE.1.0_dragonboard-410c_commander_31004980/checkout/build/tmp-glibc/work/x86_64-linux/nodejs-native/8.4.0-r0/node-v8.4.0/out'
| make: *** [node] Error 2
| ERROR: oe_runmake failed
| WARNING: /local/mnt/workspace/lnxbuild/project/trees_in_use/free_tree_le_manifest_IMM.LE.1.0_dragonboard-410c_commander_31004980/checkout/build/tmp-glibc/work/x86_64-linux/nodejs-native/8.4.0-r0/temp/run.do_compile.28276:1 exit 1 from 'exit 1'
| ERROR: Function failed: do_compile (log file is located at /local/mnt/workspace/lnxbuild/project/trees_in_use/free_tree_le_manifest_IMM.LE.1.0_dragonboard-410c_commander_31004980/checkout/build/tmp-glibc/work/x86_64-linux/nodejs-native/8.4.0-r0/temp/log.do_compile.28276)
NOTE: recipe nodejs-native-8.4.0-r0: task do_compile: Failed
```

**Comment by fboudra** [comment]
@andrey-konovalov can you have a look?

**Comment by andrey-konovalov** [comment]
@fboudra ok, will do

**Comment by mellowcandle** [comment]
@andrey-konovalov any update ?

**Comment by andrey-konovalov** [comment]
@mellowcandle thanks for the pointers, and sorry for the delayed reply.

Looking at nodejs version in your log snippet, you are using rocko.

The nodejs-8.4.0 recipe from meta-oe uses "--shared-openssl" already. So the only two options to fix the issue with the long path are:
1) not to use the long path
2) apply [the patch](https://github.com/NeoRaider/node/commit/56342b1d56e4270d1587e2e92f74a88e3802e866.patch) from https://github.com/nodejs/node/issues/9137

I've tried the 2), and it made the build to complete OK. Don't expect any breakage, but going to give this build a try on my db410c board just in case.

**Comment by andrey-konovalov** [comment]
https://github.com/96boards/meta-rpb/pull/168

**Comment by andrey-konovalov** [comment]
@mellowcandle After looking at the error log second time, I've got a question.
That "build/tmp-glibc/work/x86_64-linux/nodejs-native/8.4.0-r0/temp/log.do_compile.28276" - it doesn't look like you are using the rpb distro / setup-environment script. Otherwise it would be "build-rpb/tmp-rpb-glibc/..." or "build-rpb-wayland/tmp-rpb_wayland-glibc/..." (depending on DISTRO selected).
Are you using meta-rpb layer in your build at all (as the fix above is done in meta-rpb)? With the above fix applied, does your build/tmp-glibc/work/x86_64-linux/nodejs-native/8.4.0-r0/temp/log.do_patch has the line saying that gyp-fix-node-build-failure-with-long-build-directory-path-on-Linux.patch is applied?

**Comment by andrey-konovalov** [comment]
This is how I tested the fix:
```
repo init -u https://github.com/96boards/oe-rpb-manifest.git -b rocko
repo sync
cd layers/meta-rpb/
git remote add ynk https://github.com/andrey-konovalov/meta-rpb.git
git fetch ynk
git checkout -b ynk-rocko ynk/gyp-fix-node-build-failure-with-long-build-directory-path-on-linux
cd -
source setup-environment
# selected rpb-wayland DISTRO
bitbake rpb-weston-image
```
If I select rpb as DISTRO, and do 'bitbake rpb-desktop-image' nodejs-native builds OK as well.
