### ISSUE TITLE
Remote use of AUTOREV

### ISSUE THREAD

**Issue by ndechesne** [96boards/meta-rpb#178]
Good layers must not use AUTOREV..

layers/meta-rpb/recipes-overlayed/kselftests/kselftests-next_git.bb:SRCREV = "${AUTOREV}"
layers/meta-rpb/recipes-overlayed/ltp/ltp_git.bb:SRCREV = "${AUTOREV}"

I understand you might want to use that for LKFT.. but it should not be enabled for everyone. sorry that I missed that before. But today this specific AUTOREV broke one of the QC builds, it's not acceptable to have that without user consent..

**Comment by lumag** [comment]
AUTOREV is not used anymore, closing now.
