### ISSUE TITLE
RPB builds should generate a initramfs

### ISSUE THREAD

**Issue by petegriffin** [96boards/meta-rpb#25]
st-96b fdma driver has a requirement that a small firmware is available during kernel boot, so that dma driver can function (required by other built-in drivers such as ALSA SoC). This is achieved by placing the firmware  in the initramfs. The problem is currently RPB builds don't generate an initramfs, for us to add this firmware into.

I have pasted some discussion with ndec from IRC below on how this could be implemented: -

<ndec> griffinp: for the initramfs we simply need to create a dedicated small image. so when you compile the kernel, OE will build that image first and use it as CONFIG_INITRAMFS_SOURCE when compiling the kernel.
<ndec> so essentially, it will rely on the kernel mechanisms to build the initramfs, by providing a small rootfs
<ndec> in that rootfs we can decide what to include, for example we could put MACHINE_ESSENTIAL_EXTRA_RDEPENDS
<griffinp> ndec: ok, doesn't sound to difficult then
<ndec> I don't think there is a good image ready to use in OE for us. at least they had something for x86, but i don't think it would work out for us
<ndec> but if you need to solve it locally, then , yes, it should be trivial.
<griffinp> ndec: ideally it needs to be solved from a RPB PoV
<griffinp> ndec: but solving it locally is certainly a good start :)
<griffinp> ndec: all my dev is done outside OE, so I didn't really consider the impacts until now
<ndec> griffinp: yes, we should fix that in RPB at least.
<griffinp> ndec: is there somewhere I can create a ticket for this?
<ndec> griffinp: https://github.com/96boards/meta-rpb/issues is fine, or here https://bugs.linaro.org/enter_bug.cgi?product=Linaro%20OpenEmbedded

**Comment by koenkooi** [comment]
What about using CONFIG_EXTRA_FIRMWARE="my-blob.fw" in the kernel build? That's what that option is for.

**Comment by petegriffin** [comment]
I wasn't aware of that option, can give it a try. However looking here http://cateee.net/lkddb/web-lkddb/EXTRA_FIRMWARE.html it seems we could have licensing issues as the fdma firmware is not GPL.

**Comment by lag-linaro** [comment]
You can only bundle GPL'ed F/W using this option.

The F/W we're working with it not GPL.

**Comment by ndechesne** [comment]
regardless of this specific firmware issue, I would like to have initramfs anyways.. just saying..

**Comment by koenkooi** [comment]
The bundling issues also applies to an initramfs, what happens if you but the fw in the initramfs and then bundle the kernel + initramfs into an android-style boot.img?

**Comment by petegriffin** [comment]
FYI we aren't looking to bundle the initramfs into an android style boot.img. Having said that I don't fully understand why it would be an issue even if we were looking to do this.

From looking at mkbootimg tool it appears to add a header and concatenate the kernel image and ramdisk, and potentially other things such as a secondary bootloader into boot.img. It doesn't appear to re-link the ramdisk into the kernel image.

As Nico says, regardless of this specific issue which is obviously of interest to me personally, there is a more general point of people wanting an initramfs.

**Comment by ndechesne** [comment]
i think that what koen wanted to say is that we can have an initramfs without the need to bundle it into the kernel image with the kernel CONFIG_INITRAMFS_SOURCE. At least for RPB and for the current boards that we work with , that should be enough. But would that work for you as well ?

**Comment by petegriffin** [comment]
I thought initially CONFIG_INITRAMFS_SOURCE would suffice, and it definitely 'works'. But whether it is acceptable from a legal GPL point of view I'm unsure. Looking at linux/usr/initramfs_data.S it would appear that it is implemented by linking the resulting cpio into the kernel image.

However it looks like you can provide the initramfs to the kernel externally, via the bootloader and kernel parameter which will override any internally linked one. This should then definitely avoid any GPL issue. However it does rely on a initramfs having been generated in the first place :)

**Comment by fboudra** [comment]
What's the status of this bug?

**Comment by petegriffin** [comment]
As far as I'm aware RPB still doesn't generate a initramfs (although I haven't followed RPB that closely)?

**Comment by fboudra** [comment]
no, oe rpb still doesn't generate an initramfs. how have we fixed the issue on Debian? I don't see anything special done on the other build wrt st-96b fdma driver.

**Comment by petegriffin** [comment]
I've not been involved with the Debian build, but would assume that means FDMA and therefore ALSA audio is *not* functional.

For OE we have to patch the kernel with a (non upstreamable) patch to get the firmware loading mechamism working properly. The initramfs idea here was an attempt to allow us to drop this patch.

**Comment by fboudra** [comment]
Closing this issue since we can now generate initramfs images with OE RPB.
