### ISSUE TITLE
Missing 'release' branches

### ISSUE THREAD

**Issue by ndechesne** [96boards/meta-rpb#5]
we need to create (and maintain) stable release branches for meta-rpb, e.g. jethro and krogoth, on top of master..

**Comment by ndechesne** [comment]
We have this in rpb.inc
DISTRO_VERSION = "2.0+linaro"
2.0 release was correct when we were doing jethro based builds, but it should be 2.1 now. However we still have no release branch, only master..

**Comment by ndechesne** [comment]
@koenkooi are you looking (or planning to look) into this one? we created the release branch on meta-96boards, but not here yet.

**Comment by koenkooi** [comment]
Yes, we really need them.

**Comment by lumag** [comment]
@ndechesne probably this can be closed now, can't it?
