### ISSUE TITLE
master branch switched to gcc linaro 6.3

### ISSUE THREAD

**Issue by ndechesne** [96boards/meta-rpb#64]
meta-linaro moved to linaro gcc 6.3, but rpb.conf has 

GCCVERSION ?= "linaro-6.2"

I am seeing this when building master:

NOTE: preferred version linaro-6.2 of gcc-runtime not available (for item virtual/aarch64-linaro-linux-compilerlibs)
NOTE: versions of gcc-runtime available: 5.4.0 6.3.0 linaro-4.9 linaro-5.2 linaro-5.3 linaro-6.3
NOTE: preferred version linaro-6.2 of gcc-cross-aarch64 not available (for item virtual/aarch64-linaro-linux-gcc)
NOTE: versions of gcc-cross-aarch64 available: 5.4.0 6.3.0 linaro-4.9 linaro-5.2 linaro-5.3 linaro-6.3
NOTE: preferred version linaro-6.2 of libgcc-initial not available (for item libgcc-initial)
NOTE: versions of libgcc-initial available: 5.4.0 6.3.0 linaro-4.9 linaro-5.2 linaro-5.3 linaro-6.3
NOTE: preferred version linaro-6.2 of libgcc not available (for item libgcc)
NOTE: versions of libgcc available: 5.4.0 6.3.0 linaro-4.9 linaro-5.2 linaro-5.3 linaro-6.3
NOTE: preferred version linaro-6.2 of gcc-cross-initial-aarch64 not available (for item virtual/aarch64-linaro-linux-gcc-initial)
NOTE: versions of gcc-cross-initial-aarch64 available: 5.4.0 6.3.0 linaro-4.9 linaro-5.2 linaro-5.3 linaro-6.3
NOTE: preferred version linaro-6.2 of gcc-cross-aarch64 not available (for item virtual/aarch64-linaro-linux-g++)
NOTE: versions of gcc-cross-aarch64 available: 5.4.0 6.3.0 linaro-4.9 linaro-5.2 linaro-5.3 linaro-6.3
NOTE: preferred version linaro-6.2 of libgcc not available (for item libgcc)
NOTE: versions of libgcc available: 5.4.0 6.3.0 linaro-4.9 linaro-5.2 linaro-5.3 linaro-6.3

**Comment by koenkooi** [comment]
#65 should fix this

**Comment by fboudra** [comment]
fixed with https://github.com/96boards/meta-rpb/commit/9c88ddb24f0d22a44b9cd76dcfffa6da2aa21033
